[build]
  base = "bz-front-development"
  publish = "dist"
  command = "npm install --no-audit --no-fund --legacy-peer-deps && npm run build:ci"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


