"""init

Revision ID: 748f230d5c9b
Revises: 
Create Date: 2025-08-15 10:11:12.185233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748f230d5c9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groupss', schema=None) as batch_op:
        batch_op.drop_column('base_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groupss', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_class', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
